// Code generated by ogen, DO NOT EDIT.
package openapi

type GetFiMetadataByPrefixRes interface {
	getFiMetadataByPrefixRes()
}

type GetFiMetadataByProfilesRes interface {
	getFiMetadataByProfilesRes()
}

type GetFiObjectRes interface {
	getFiObjectRes()
}
