// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
)

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Machine readable error code.
// Ref: #/components/schemas/ErrorCode
type ErrorCode string

const (
	ErrorCodePROFILEIDCURSORLENGTH ErrorCode = "PROFILE_ID_CURSOR_LENGTH"
	ErrorCodeKEYNOTFOUND           ErrorCode = "KEY_NOT_FOUND"
	ErrorCodeFATALERROR            ErrorCode = "FATAL_ERROR"
)

// AllValues returns all ErrorCode values.
func (ErrorCode) AllValues() []ErrorCode {
	return []ErrorCode{
		ErrorCodePROFILEIDCURSORLENGTH,
		ErrorCodeKEYNOTFOUND,
		ErrorCodeFATALERROR,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorCodePROFILEIDCURSORLENGTH:
		return []byte(s), nil
	case ErrorCodeKEYNOTFOUND:
		return []byte(s), nil
	case ErrorCodeFATALERROR:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorCode) UnmarshalText(data []byte) error {
	switch ErrorCode(data) {
	case ErrorCodePROFILEIDCURSORLENGTH:
		*s = ErrorCodePROFILEIDCURSORLENGTH
		return nil
	case ErrorCodeKEYNOTFOUND:
		*s = ErrorCodeKEYNOTFOUND
		return nil
	case ErrorCodeFATALERROR:
		*s = ErrorCodeFATALERROR
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ErrorResp
type ErrorResp struct {
	ErrorCode ErrorCode `json:"errorCode"`
	ErrorDesc string    `json:"errorDesc"`
}

// GetErrorCode returns the value of ErrorCode.
func (s *ErrorResp) GetErrorCode() ErrorCode {
	return s.ErrorCode
}

// GetErrorDesc returns the value of ErrorDesc.
func (s *ErrorResp) GetErrorDesc() string {
	return s.ErrorDesc
}

// SetErrorCode sets the value of ErrorCode.
func (s *ErrorResp) SetErrorCode(val ErrorCode) {
	s.ErrorCode = val
}

// SetErrorDesc sets the value of ErrorDesc.
func (s *ErrorResp) SetErrorDesc(val string) {
	s.ErrorDesc = val
}

// Ref: #/components/schemas/FiObject
type FiObject struct {
	ProfileId   string    `json:"profileId"`
	Timestamp   time.Time `json:"timestamp"`
	OriginTopic string    `json:"originTopic"`
	// Arbitrary JSON payload.
	Data FiObjectData `json:"data"`
}

// GetProfileId returns the value of ProfileId.
func (s *FiObject) GetProfileId() string {
	return s.ProfileId
}

// GetTimestamp returns the value of Timestamp.
func (s *FiObject) GetTimestamp() time.Time {
	return s.Timestamp
}

// GetOriginTopic returns the value of OriginTopic.
func (s *FiObject) GetOriginTopic() string {
	return s.OriginTopic
}

// GetData returns the value of Data.
func (s *FiObject) GetData() FiObjectData {
	return s.Data
}

// SetProfileId sets the value of ProfileId.
func (s *FiObject) SetProfileId(val string) {
	s.ProfileId = val
}

// SetTimestamp sets the value of Timestamp.
func (s *FiObject) SetTimestamp(val time.Time) {
	s.Timestamp = val
}

// SetOriginTopic sets the value of OriginTopic.
func (s *FiObject) SetOriginTopic(val string) {
	s.OriginTopic = val
}

// SetData sets the value of Data.
func (s *FiObject) SetData(val FiObjectData) {
	s.Data = val
}

func (*FiObject) getFiObjectRes() {}

// Arbitrary JSON payload.
type FiObjectData map[string]jx.Raw

func (s *FiObjectData) init() FiObjectData {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Subject filter value.
// Ref: #/components/schemas/FiSubject
type FiSubject string

const (
	FiSubjectConnections  FiSubject = "connections"
	FiSubjectAccounts     FiSubject = "accounts"
	FiSubjectTransactions FiSubject = "transactions"
	FiSubjectHoldings     FiSubject = "holdings"
)

// AllValues returns all FiSubject values.
func (FiSubject) AllValues() []FiSubject {
	return []FiSubject{
		FiSubjectConnections,
		FiSubjectAccounts,
		FiSubjectTransactions,
		FiSubjectHoldings,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s FiSubject) MarshalText() ([]byte, error) {
	switch s {
	case FiSubjectConnections:
		return []byte(s), nil
	case FiSubjectAccounts:
		return []byte(s), nil
	case FiSubjectTransactions:
		return []byte(s), nil
	case FiSubjectHoldings:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *FiSubject) UnmarshalText(data []byte) error {
	switch FiSubject(data) {
	case FiSubjectConnections:
		*s = FiSubjectConnections
		return nil
	case FiSubjectAccounts:
		*s = FiSubjectAccounts
		return nil
	case FiSubjectTransactions:
		*s = FiSubjectTransactions
		return nil
	case FiSubjectHoldings:
		*s = FiSubjectHoldings
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetFiMetadataByPrefixBadRequest ErrorResp

func (*GetFiMetadataByPrefixBadRequest) getFiMetadataByPrefixRes() {}

type GetFiMetadataByPrefixInternalServerError ErrorResp

func (*GetFiMetadataByPrefixInternalServerError) getFiMetadataByPrefixRes() {}

type GetFiMetadataByProfilesBadRequest ErrorResp

func (*GetFiMetadataByProfilesBadRequest) getFiMetadataByProfilesRes() {}

type GetFiMetadataByProfilesInternalServerError ErrorResp

func (*GetFiMetadataByProfilesInternalServerError) getFiMetadataByProfilesRes() {}

type GetFiObjectInternalServerError ErrorResp

func (*GetFiObjectInternalServerError) getFiObjectRes() {}

type GetFiObjectNotFound ErrorResp

func (*GetFiObjectNotFound) getFiObjectRes() {}

// Ref: #/components/schemas/ListFiMetadataResponse
type ListFiMetadataResponse struct {
	OpsFiMetadata []OpsFiMetadata `json:"opsFiMetadata"`
	// Comma seperated cursor that can be passed back into the list fi metadata call.
	Cursor string `json:"cursor"`
}

// GetOpsFiMetadata returns the value of OpsFiMetadata.
func (s *ListFiMetadataResponse) GetOpsFiMetadata() []OpsFiMetadata {
	return s.OpsFiMetadata
}

// GetCursor returns the value of Cursor.
func (s *ListFiMetadataResponse) GetCursor() string {
	return s.Cursor
}

// SetOpsFiMetadata sets the value of OpsFiMetadata.
func (s *ListFiMetadataResponse) SetOpsFiMetadata(val []OpsFiMetadata) {
	s.OpsFiMetadata = val
}

// SetCursor sets the value of Cursor.
func (s *ListFiMetadataResponse) SetCursor(val string) {
	s.Cursor = val
}

func (*ListFiMetadataResponse) getFiMetadataByPrefixRes()   {}
func (*ListFiMetadataResponse) getFiMetadataByProfilesRes() {}

// Ref: #/components/schemas/OpsFiMetadata
type OpsFiMetadata struct {
	Subject           FiSubject `json:"subject"`
	Key               string    `json:"key"`
	LastModified      time.Time `json:"lastModified"`
	ProfileID         string    `json:"profileID"`
	ProviderAccountID string    `json:"providerAccountID"`
	PartyIDTypeCd     string    `json:"partyIDTypeCd"`
	AccountID         string    `json:"accountID"`
	ElementID         string    `json:"elementID"`
	LastUpdated       time.Time `json:"lastUpdated"`
}

// GetSubject returns the value of Subject.
func (s *OpsFiMetadata) GetSubject() FiSubject {
	return s.Subject
}

// GetKey returns the value of Key.
func (s *OpsFiMetadata) GetKey() string {
	return s.Key
}

// GetLastModified returns the value of LastModified.
func (s *OpsFiMetadata) GetLastModified() time.Time {
	return s.LastModified
}

// GetProfileID returns the value of ProfileID.
func (s *OpsFiMetadata) GetProfileID() string {
	return s.ProfileID
}

// GetProviderAccountID returns the value of ProviderAccountID.
func (s *OpsFiMetadata) GetProviderAccountID() string {
	return s.ProviderAccountID
}

// GetPartyIDTypeCd returns the value of PartyIDTypeCd.
func (s *OpsFiMetadata) GetPartyIDTypeCd() string {
	return s.PartyIDTypeCd
}

// GetAccountID returns the value of AccountID.
func (s *OpsFiMetadata) GetAccountID() string {
	return s.AccountID
}

// GetElementID returns the value of ElementID.
func (s *OpsFiMetadata) GetElementID() string {
	return s.ElementID
}

// GetLastUpdated returns the value of LastUpdated.
func (s *OpsFiMetadata) GetLastUpdated() time.Time {
	return s.LastUpdated
}

// SetSubject sets the value of Subject.
func (s *OpsFiMetadata) SetSubject(val FiSubject) {
	s.Subject = val
}

// SetKey sets the value of Key.
func (s *OpsFiMetadata) SetKey(val string) {
	s.Key = val
}

// SetLastModified sets the value of LastModified.
func (s *OpsFiMetadata) SetLastModified(val time.Time) {
	s.LastModified = val
}

// SetProfileID sets the value of ProfileID.
func (s *OpsFiMetadata) SetProfileID(val string) {
	s.ProfileID = val
}

// SetProviderAccountID sets the value of ProviderAccountID.
func (s *OpsFiMetadata) SetProviderAccountID(val string) {
	s.ProviderAccountID = val
}

// SetPartyIDTypeCd sets the value of PartyIDTypeCd.
func (s *OpsFiMetadata) SetPartyIDTypeCd(val string) {
	s.PartyIDTypeCd = val
}

// SetAccountID sets the value of AccountID.
func (s *OpsFiMetadata) SetAccountID(val string) {
	s.AccountID = val
}

// SetElementID sets the value of ElementID.
func (s *OpsFiMetadata) SetElementID(val string) {
	s.ElementID = val
}

// SetLastUpdated sets the value of LastUpdated.
func (s *OpsFiMetadata) SetLastUpdated(val time.Time) {
	s.LastUpdated = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
