// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// GetFiMetadataByPrefixParams is parameters of getFiMetadataByPrefix operation.
type GetFiMetadataByPrefixParams struct {
	// Prefix to perform search with.
	Prefix string
	// Cursor to paginate by. Remember to url encode it, ListObjectsV2 cursors contain unsafe URL
	// characters.
	Cursor OptString `json:",omitempty,omitzero"`
	// Subject filter value.
	Subject FiSubject
}

func unpackGetFiMetadataByPrefixParams(packed middleware.Parameters) (params GetFiMetadataByPrefixParams) {
	{
		key := middleware.ParameterKey{
			Name: "prefix",
			In:   "query",
		}
		params.Prefix = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Cursor = v.(OptString)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "subject",
			In:   "query",
		}
		params.Subject = packed[key].(FiSubject)
	}
	return params
}

func decodeGetFiMetadataByPrefixParams(args [0]string, argsEscaped bool, r *http.Request) (params GetFiMetadataByPrefixParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: prefix.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "prefix",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Prefix = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "prefix",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCursorVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCursorVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Cursor.SetTo(paramsDotCursorVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: subject.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "subject",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Subject = FiSubject(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Subject.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subject",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetFiMetadataByProfilesParams is parameters of getFiMetadataByProfiles operation.
type GetFiMetadataByProfilesParams struct {
	// Profile IDs to filter by (comma-separated string).
	ProfileIDs string
	// Cursors to paginate by (comma-seperated string). Remember to url encode it, ListObjectsV2 cursors
	// contain unsafe URL characters.
	Cursor string
	// Subject filter value.
	Subject FiSubject
}

func unpackGetFiMetadataByProfilesParams(packed middleware.Parameters) (params GetFiMetadataByProfilesParams) {
	{
		key := middleware.ParameterKey{
			Name: "profileIDs",
			In:   "query",
		}
		params.ProfileIDs = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "cursor",
			In:   "query",
		}
		params.Cursor = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "subject",
			In:   "query",
		}
		params.Subject = packed[key].(FiSubject)
	}
	return params
}

func decodeGetFiMetadataByProfilesParams(args [0]string, argsEscaped bool, r *http.Request) (params GetFiMetadataByProfilesParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: profileIDs.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "profileIDs",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProfileIDs = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "profileIDs",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cursor.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cursor",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Cursor = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cursor",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: subject.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "subject",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Subject = FiSubject(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Subject.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subject",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetFiObjectParams is parameters of getFiObject operation.
type GetFiObjectParams struct {
	// Key identifying the FI object.
	Key string
	// Subject filter value.
	Subject FiSubject
}

func unpackGetFiObjectParams(packed middleware.Parameters) (params GetFiObjectParams) {
	{
		key := middleware.ParameterKey{
			Name: "key",
			In:   "query",
		}
		params.Key = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "subject",
			In:   "query",
		}
		params.Subject = packed[key].(FiSubject)
	}
	return params
}

func decodeGetFiObjectParams(args [0]string, argsEscaped bool, r *http.Request) (params GetFiObjectParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: key.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "key",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Key = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "key",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: subject.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "subject",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Subject = FiSubject(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Subject.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "subject",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
