// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	GetFiMetadataByPrefixOperation   OperationName = "GetFiMetadataByPrefix"
	GetFiMetadataByProfilesOperation OperationName = "GetFiMetadataByProfiles"
	GetFiObjectOperation             OperationName = "GetFiObject"
)
