// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s ErrorCode) Validate() error {
	switch s {
	case "PROFILE_ID_CURSOR_LENGTH":
		return nil
	case "KEY_NOT_FOUND":
		return nil
	case "FATAL_ERROR":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ErrorResp) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.ErrorCode.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "errorCode",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s FiSubject) Validate() error {
	switch s {
	case "connections":
		return nil
	case "accounts":
		return nil
	case "transactions":
		return nil
	case "holdings":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *GetFiMetadataByPrefixBadRequest) Validate() error {
	alias := (*ErrorResp)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetFiMetadataByPrefixInternalServerError) Validate() error {
	alias := (*ErrorResp)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetFiMetadataByProfilesBadRequest) Validate() error {
	alias := (*ErrorResp)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetFiMetadataByProfilesInternalServerError) Validate() error {
	alias := (*ErrorResp)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetFiObjectInternalServerError) Validate() error {
	alias := (*ErrorResp)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetFiObjectNotFound) Validate() error {
	alias := (*ErrorResp)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ListFiMetadataResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.OpsFiMetadata == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.OpsFiMetadata {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "opsFiMetadata",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *OpsFiMetadata) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Subject.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "subject",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}
