// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetFiMetadataByPrefix implements getFiMetadataByPrefix operation.
//
// Returns a list of FI metadata records filtered by query parameters.
//
// GET /fimetadata/prefix
func (UnimplementedHandler) GetFiMetadataByPrefix(ctx context.Context, params GetFiMetadataByPrefixParams) (r GetFiMetadataByPrefixRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFiMetadataByProfiles implements getFiMetadataByProfiles operation.
//
// Returns a list of FI metadata records filtered by query parameters.
//
// GET /fimetadata/profiles
func (UnimplementedHandler) GetFiMetadataByProfiles(ctx context.Context, params GetFiMetadataByProfilesParams) (r GetFiMetadataByProfilesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetFiObject implements getFiObject operation.
//
// Returns the FI object data for the given key and subject.
//
// GET /fiobject
func (UnimplementedHandler) GetFiObject(ctx context.Context, params GetFiObjectParams) (r GetFiObjectRes, _ error) {
	return r, ht.ErrNotImplemented
}
