// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetFiMetadataByPrefix implements getFiMetadataByPrefix operation.
	//
	// Returns a list of FI metadata records filtered by query parameters.
	//
	// GET /fimetadata/prefix
	GetFiMetadataByPrefix(ctx context.Context, params GetFiMetadataByPrefixParams) (GetFiMetadataByPrefixRes, error)
	// GetFiMetadataByProfiles implements getFiMetadataByProfiles operation.
	//
	// Returns a list of FI metadata records filtered by query parameters.
	//
	// GET /fimetadata/profiles
	GetFiMetadataByProfiles(ctx context.Context, params GetFiMetadataByProfilesParams) (GetFiMetadataByProfilesRes, error)
	// GetFiObject implements getFiObject operation.
	//
	// Returns the FI object data for the given key and subject.
	//
	// GET /fiobject
	GetFiObject(ctx context.Context, params GetFiObjectParams) (GetFiObjectRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
