// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: messages.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtnCnctEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrtyId        string                 `protobuf:"bytes,1,opt,name=prty_id,json=prtyId,proto3" json:"prty_id,omitempty"`
	PrtyIdTypeCd  string                 `protobuf:"bytes,2,opt,name=prty_id_type_cd,json=prtyIdTypeCd,proto3" json:"prty_id_type_cd,omitempty"`
	ExtnCnctId    string                 `protobuf:"bytes,3,opt,name=extn_cnct_id,json=extnCnctId,proto3" json:"extn_cnct_id,omitempty"`
	BusDt         string                 `protobuf:"bytes,4,opt,name=bus_dt,json=busDt,proto3" json:"bus_dt,omitempty"`
	VendorName    string                 `protobuf:"bytes,5,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"` // todo: add the rest of the fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtnCnctEntity) Reset() {
	*x = ExtnCnctEntity{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtnCnctEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtnCnctEntity) ProtoMessage() {}

func (x *ExtnCnctEntity) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtnCnctEntity.ProtoReflect.Descriptor instead.
func (*ExtnCnctEntity) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ExtnCnctEntity) GetPrtyId() string {
	if x != nil {
		return x.PrtyId
	}
	return ""
}

func (x *ExtnCnctEntity) GetPrtyIdTypeCd() string {
	if x != nil {
		return x.PrtyIdTypeCd
	}
	return ""
}

func (x *ExtnCnctEntity) GetExtnCnctId() string {
	if x != nil {
		return x.ExtnCnctId
	}
	return ""
}

func (x *ExtnCnctEntity) GetBusDt() string {
	if x != nil {
		return x.BusDt
	}
	return ""
}

func (x *ExtnCnctEntity) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

type ExtnAcctEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrtyId        string                 `protobuf:"bytes,2,opt,name=prty_id,json=prtyId,proto3" json:"prty_id,omitempty"`
	PrtyIdTypeCd  string                 `protobuf:"bytes,3,opt,name=prty_id_type_cd,json=prtyIdTypeCd,proto3" json:"prty_id_type_cd,omitempty"`
	ExtnCnctId    string                 `protobuf:"bytes,4,opt,name=extn_cnct_id,json=extnCnctId,proto3" json:"extn_cnct_id,omitempty"`
	ExtnAcctId    string                 `protobuf:"bytes,5,opt,name=extn_acct_id,json=extnAcctId,proto3" json:"extn_acct_id,omitempty"`
	BusDt         string                 `protobuf:"bytes,6,opt,name=bus_dt,json=busDt,proto3" json:"bus_dt,omitempty"`
	AcctName      string                 `protobuf:"bytes,7,opt,name=acct_name,json=acctName,proto3" json:"acct_name,omitempty"` // todo: add the rest of the fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtnAcctEntity) Reset() {
	*x = ExtnAcctEntity{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtnAcctEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtnAcctEntity) ProtoMessage() {}

func (x *ExtnAcctEntity) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtnAcctEntity.ProtoReflect.Descriptor instead.
func (*ExtnAcctEntity) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ExtnAcctEntity) GetPrtyId() string {
	if x != nil {
		return x.PrtyId
	}
	return ""
}

func (x *ExtnAcctEntity) GetPrtyIdTypeCd() string {
	if x != nil {
		return x.PrtyIdTypeCd
	}
	return ""
}

func (x *ExtnAcctEntity) GetExtnCnctId() string {
	if x != nil {
		return x.ExtnCnctId
	}
	return ""
}

func (x *ExtnAcctEntity) GetExtnAcctId() string {
	if x != nil {
		return x.ExtnAcctId
	}
	return ""
}

func (x *ExtnAcctEntity) GetBusDt() string {
	if x != nil {
		return x.BusDt
	}
	return ""
}

func (x *ExtnAcctEntity) GetAcctName() string {
	if x != nil {
		return x.AcctName
	}
	return ""
}

type ExtnHoldEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrtyId        string                 `protobuf:"bytes,2,opt,name=prty_id,json=prtyId,proto3" json:"prty_id,omitempty"`
	PrtyIdTypeCd  string                 `protobuf:"bytes,3,opt,name=prty_id_type_cd,json=prtyIdTypeCd,proto3" json:"prty_id_type_cd,omitempty"`
	ExtnAcctId    string                 `protobuf:"bytes,4,opt,name=extn_acct_id,json=extnAcctId,proto3" json:"extn_acct_id,omitempty"`
	ExtnHoldId    string                 `protobuf:"bytes,5,opt,name=extn_hold_id,json=extnHoldId,proto3" json:"extn_hold_id,omitempty"`
	BusDt         string                 `protobuf:"bytes,6,opt,name=bus_dt,json=busDt,proto3" json:"bus_dt,omitempty"`
	HoldName      string                 `protobuf:"bytes,7,opt,name=hold_name,json=holdName,proto3" json:"hold_name,omitempty"` // todo: add the rest of the fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtnHoldEntity) Reset() {
	*x = ExtnHoldEntity{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtnHoldEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtnHoldEntity) ProtoMessage() {}

func (x *ExtnHoldEntity) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtnHoldEntity.ProtoReflect.Descriptor instead.
func (*ExtnHoldEntity) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ExtnHoldEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtnHoldEntity) GetPrtyId() string {
	if x != nil {
		return x.PrtyId
	}
	return ""
}

func (x *ExtnHoldEntity) GetPrtyIdTypeCd() string {
	if x != nil {
		return x.PrtyIdTypeCd
	}
	return ""
}

func (x *ExtnHoldEntity) GetExtnAcctId() string {
	if x != nil {
		return x.ExtnAcctId
	}
	return ""
}

func (x *ExtnHoldEntity) GetExtnHoldId() string {
	if x != nil {
		return x.ExtnHoldId
	}
	return ""
}

func (x *ExtnHoldEntity) GetBusDt() string {
	if x != nil {
		return x.BusDt
	}
	return ""
}

func (x *ExtnHoldEntity) GetHoldName() string {
	if x != nil {
		return x.HoldName
	}
	return ""
}

type ExtnTxnEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PrtyId        string                 `protobuf:"bytes,2,opt,name=prty_id,json=prtyId,proto3" json:"prty_id,omitempty"`
	PrtyIdTypeCd  string                 `protobuf:"bytes,3,opt,name=prty_id_type_cd,json=prtyIdTypeCd,proto3" json:"prty_id_type_cd,omitempty"`
	ExtnAcctId    string                 `protobuf:"bytes,4,opt,name=extn_acct_id,json=extnAcctId,proto3" json:"extn_acct_id,omitempty"`
	ExtnTxnId     string                 `protobuf:"bytes,5,opt,name=extn_txn_id,json=extnTxnId,proto3" json:"extn_txn_id,omitempty"`
	TxnDt         string                 `protobuf:"bytes,6,opt,name=txn_dt,json=txnDt,proto3" json:"txn_dt,omitempty"`
	BusDt         string                 `protobuf:"bytes,7,opt,name=bus_dt,json=busDt,proto3" json:"bus_dt,omitempty"`
	TxnAmt        int64                  `protobuf:"varint,8,opt,name=txn_amt,json=txnAmt,proto3" json:"txn_amt,omitempty"` // todo: add the rest of the fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtnTxnEntity) Reset() {
	*x = ExtnTxnEntity{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtnTxnEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtnTxnEntity) ProtoMessage() {}

func (x *ExtnTxnEntity) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtnTxnEntity.ProtoReflect.Descriptor instead.
func (*ExtnTxnEntity) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ExtnTxnEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExtnTxnEntity) GetPrtyId() string {
	if x != nil {
		return x.PrtyId
	}
	return ""
}

func (x *ExtnTxnEntity) GetPrtyIdTypeCd() string {
	if x != nil {
		return x.PrtyIdTypeCd
	}
	return ""
}

func (x *ExtnTxnEntity) GetExtnAcctId() string {
	if x != nil {
		return x.ExtnAcctId
	}
	return ""
}

func (x *ExtnTxnEntity) GetExtnTxnId() string {
	if x != nil {
		return x.ExtnTxnId
	}
	return ""
}

func (x *ExtnTxnEntity) GetTxnDt() string {
	if x != nil {
		return x.TxnDt
	}
	return ""
}

func (x *ExtnTxnEntity) GetBusDt() string {
	if x != nil {
		return x.BusDt
	}
	return ""
}

func (x *ExtnTxnEntity) GetTxnAmt() int64 {
	if x != nil {
		return x.TxnAmt
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\"\xaa\x01\n" +
	"\x0eExtnCnctEntity\x12\x17\n" +
	"\aprty_id\x18\x01 \x01(\tR\x06prtyId\x12%\n" +
	"\x0fprty_id_type_cd\x18\x02 \x01(\tR\fprtyIdTypeCd\x12 \n" +
	"\fextn_cnct_id\x18\x03 \x01(\tR\n" +
	"extnCnctId\x12\x15\n" +
	"\x06bus_dt\x18\x04 \x01(\tR\x05busDt\x12\x1f\n" +
	"\vvendor_name\x18\x05 \x01(\tR\n" +
	"vendorName\"\xc8\x01\n" +
	"\x0eExtnAcctEntity\x12\x17\n" +
	"\aprty_id\x18\x02 \x01(\tR\x06prtyId\x12%\n" +
	"\x0fprty_id_type_cd\x18\x03 \x01(\tR\fprtyIdTypeCd\x12 \n" +
	"\fextn_cnct_id\x18\x04 \x01(\tR\n" +
	"extnCnctId\x12 \n" +
	"\fextn_acct_id\x18\x05 \x01(\tR\n" +
	"extnAcctId\x12\x15\n" +
	"\x06bus_dt\x18\x06 \x01(\tR\x05busDt\x12\x1b\n" +
	"\tacct_name\x18\a \x01(\tR\bacctName\"\xd8\x01\n" +
	"\x0eExtnHoldEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aprty_id\x18\x02 \x01(\tR\x06prtyId\x12%\n" +
	"\x0fprty_id_type_cd\x18\x03 \x01(\tR\fprtyIdTypeCd\x12 \n" +
	"\fextn_acct_id\x18\x04 \x01(\tR\n" +
	"extnAcctId\x12 \n" +
	"\fextn_hold_id\x18\x05 \x01(\tR\n" +
	"extnHoldId\x12\x15\n" +
	"\x06bus_dt\x18\x06 \x01(\tR\x05busDt\x12\x1b\n" +
	"\thold_name\x18\a \x01(\tR\bholdName\"\xe8\x01\n" +
	"\rExtnTxnEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aprty_id\x18\x02 \x01(\tR\x06prtyId\x12%\n" +
	"\x0fprty_id_type_cd\x18\x03 \x01(\tR\fprtyIdTypeCd\x12 \n" +
	"\fextn_acct_id\x18\x04 \x01(\tR\n" +
	"extnAcctId\x12\x1e\n" +
	"\vextn_txn_id\x18\x05 \x01(\tR\textnTxnId\x12\x15\n" +
	"\x06txn_dt\x18\x06 \x01(\tR\x05txnDt\x12\x15\n" +
	"\x06bus_dt\x18\a \x01(\tR\x05busDt\x12\x17\n" +
	"\atxn_amt\x18\b \x01(\x03R\x06txnAmtB\rZ\vfilogger/pbb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_proto_goTypes = []any{
	(*ExtnCnctEntity)(nil), // 0: messages.ExtnCnctEntity
	(*ExtnAcctEntity)(nil), // 1: messages.ExtnAcctEntity
	(*ExtnHoldEntity)(nil), // 2: messages.ExtnHoldEntity
	(*ExtnTxnEntity)(nil),  // 3: messages.ExtnTxnEntity
}
var file_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
