name: Deploy to Amazon ECS TEST

on:
  push:
    branches:
      - main

env:
  TF_WORKING_DIR: infra/environments/test
  AWS_REGION: us-east-1
  TF_VERSION: 1.7.0
  ECR_REPOSITORY: development/yodlee-ops

jobs:
  build:
    name: Build app (CI)
    runs-on: ubuntu-latest
    environment: Test

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install codegen prereqs with Make
        run: make install

      - name: Generate sources with Make
        run: make

      - name: Run tests with Make
        run: make tests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

  deploy:
    name:  Deploy app (CD)
    runs-on: ubuntu-latest
    environment: Test
    needs: [ build ]
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}
    env:
      TF_VAR_commit_sha: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve tfplan

      - name: Upload plan artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          retention-days: 30